[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vml"
version = "1.1.1"
authors = [{name = "sdkurjnk"}]
license = {text = "MIT"}
description = "A Variable Monitoring Logger with C-Engine"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["logging", "monitoring", "c-extension"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Debuggers"
]

[project.urls]
Homepage = "https://github.com/sdkurjnk/Variable_Monitering_Logger"

[tool.setuptools]
package-dir = {"" = "src"}
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]