[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vml"
version = "1.0.3"
authors = [{name = "sdkurjnk"}]
description = "A Variable Monitoring Logger with C-Engine and Visualizer"
readme = "README.md"
requires-python = ">=3.11"
keywords = ["logging", "monitoring", "c-extension"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Debuggers"
]

[tool.setuptools]
package-dir = {"" = "src"}
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]